### ISSUE TITLE
Bug: open random note from search creates new empty .md files for non-.md files

### ISSUE THREAD

**Issue by pjeby** [erichalldev/obsidian-smart-random-note#14] opened 2021-04-13 05:38 UTC
Steps to reproduce:

* Search for image files or other file extensions
* Click the ribbon icon to select one at random

Result: A new markdown note is created in the vault using the base name of the file from the search, and then opened.

Expected result: the file is opened in the correct viewer for that file type, or skipped if not supported.

Workaround: add `file:.md` to the search to guarantee only notes are selected

**Comment by erichalldev** [comment] 2021-07-01 13:38
Thank you for the feedback! I'm sorry it took so long to get back to you. I was able to reproduce this issue. I'll look into what it takes to open different file types. If that looks like it'll be too difficult, I'll not open the non-markdown files and show an alert so the user knows what happened.

**Comment by pjeby** [comment] 2021-07-01 17:36
You can use [`app.workspace.openLinkText()`](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L3246) with the file's `.path` and an empty string, to automatically open the file with the right view type.

If the type is unsupported, it will be opened in the OS default app, however, so you may wish to check `app.viewRegistry.typeByExtension[ext]` to see if it has a view type or not.  If not, then a notice would be appropriate so as not to unintentionally launch files or scripts with possible unintended or harmful consequences.

**Comment by erichalldev** [comment] 2021-07-07 15:34
Thanks for the tip, this is good stuff! I'll see what I can do.

**Comment by erichalldev** [comment] 2021-07-08 13:42
This is resolved in release 0.2.2. I decided to go the strict route of only opening markdown files. In the future I can look at all the edge cases of trying to open a non-markdown file either in Obsidian or in its native application.

**Closed by erichalldev** 2021-07-08 13:42 UTC
Labels: bug
